#ifndef _RESOURCE_H
#define _RESOURCE_H

enum{
	//INX_QUIT = wxID_EXIT,
	INX_NEW_PROJECT = 101,
	INX_OPEN_PROJECT,
	INX_SAVE_PROJECT,
    INX_REFRESH,
    INX_CHANGE_TITLE,
    INX_CHANGE_POSITION,
    INX_CHANGE_SIZE,
    INX_CHILD_QUIT,
   // INX_ABOUT = wxID_ABOUT
};

#define IDAPPLY                         3
#define ID_DELETE                       3
#define IDD_ABOUTBOX                    100
#define IDD_PROJECTDIALOG               111
#define ID_INDICATOR_LOCALHOST          112
#define IDR_MAINFRAME                   128
#define IDR_GUITYPE                     129
#define IDR_DRAWPRTYPE                  129
#define IDD_ControlDef                  130
#define IDD_CHOOSE                      130
#define IDB_GREY                        131
#define IDD_DATA                        131
#define IDBLGB_BITMAP1                  132
#define IDB_RED                         132
#define IDBLGB_BITMAP2                  133
#define IDB_GREEN                       133
#define IDBLGB_BITMAP3                  134
#define IDD_TAGS                        134
#define IDBLGB_BITMAP4                  135
#define IDBLGB_BITMAP5                  136
#define IDBLGB_BITMAP6                  137
#define IDD_DIALOG1                     137
#define IDBLGB_BITMAP7                  138
#define IDD_DIALOG2                     138
#define IDBLGB_BITMAP8                  139
#define IDBLGB_BITMAP9                  140
#define IDD_DATASRC                     140
#define IDBLGB_BITMAP10                 141
#define IDB_BLUE                        141
#define IDBLGB_BITMAP11                 142
#define IDB_BLACK                       142
#define IDD_PARAMETERS                  142
#define IDBLGB_BITMAP12                 143
#define IDB_YELLOW                      143
#define IDR_remove                      143
#define IDBLGB_BITMAP13                 144
#define IDB_WHITE                       144
#define IDR_ICON_MENU                   144
#define IDBLGB_BITMAP14                 145
#define IDBLGB_BITMAP21                 145
#define IDD_ENCAPSULATE                 145
#define IDBLGB_BITMAP15                 146
#define IDD_FTP_OPTIONS                 146
#define IDBLGB_BITMAP16                 147
#define IDD_COLOUR_KEY                  147
#define IDBLGB_BITMAP17                 148
#define IDBLGB_BITMAP18                 149
#define IDB_GREYICON                    149
#define IDBLGB_BITMAP19                 150
#define IDD_PROPERTIES_TEXTBOX          150
#define IDBLGB_BITMAP20                 151
#define IDD_PROPERTIES_IMAGE            151
#define IDB_BLUEICON                    152
#define IDD_DELETE_GUI_FILE             153
#define IDB_YELLOWICON                  153
#define IDD_CREATE_GUIFILE              154
#define IDB_PURPLEICON                  154
#define IDD_PROJ_FILE_MGR               155
#define IDD_LGBTRANSFER_TARGET          156
#define IDBLGB_DIALOG_TESTER            157
#define IDB_LINES                       158
#define IDBLGB_DIALOG1                  160
#define IDD_FORCE_VALUE                 160
#define IDD_GOTO_TIME                   161
#define IDBLGB_DIALOG_SCRNTAGTEST       162
#define IDD_COPY_GUIFILE                163
#define IDD_DEBUG_MSG                   164
#define IDR_TOOLBAR1                    166
#define IDB_BITMAP1                     166
#define IDD_INSTANCE_NAME               167
#define IDBLGB_ICON_MENU                168
#define IDD_BLOCK_NAME                  168
#define IDD_COMPONENT_NAME              168
#define IDD_ADD_PORT                    169
#define IDD_PORT_LABEL                  170
#define IDB_BITMAP2                     179
#define IDD_TAG_LINE                    180
#define IDD_ZOOM                        182
#define IDD_GROUP_SETUP                 183
#define IDD_EDIT_GROUP                  184
#define IDD_SELECT_GROUP                185
#define IDD_EXPORT                      186
#define IDD_DIALOG4                     187
#define IDD_DIALOG3                     188
#define IDD_LIBRARY_CHOOSER             189
#define IDD_CHOOSE1                     195
#define IDD_CHOOSE_BLOCK                195
#define IDD_BLOCK_PORT_LABEL            196
#define IDD_WIDGET_GROUP_NAME           197
#define IDC_CURSOR_LABBLOCK             198
#define IDC_CURSOR_LABPORT              199
#define IDC_CURSOR_LABNODE              200
#define IDC_CURSOR_LABLINE              201
#define IDD_DIALOG6                     202
#define IDD_MENU_NAME                   203
#define IDB_TREEICON_A1                 206
#define IDI_ICON1                       207
#define IDB_TREEICON_B1                 208
#define IDB_TREEICON_C1                 209
#define IDB_TREEICON_D1                 210
#define IDB_TREEICON_E1                 211
#define IDI_LED_ON                      212
#define IDB_TREEICON_D2                 213
#define IDI_LEDOFF                      213
#define IDI_LED_OFF                     213
#define IDB_TREEICON_C2                 214
#define IDB_TREEICON_B2                 215
#define IDB_TREEICON_A2                 216
#define IDB_TREEICON_E2                 217
#define IDB_TREEICON_DEFAULT            218
#define IDB_TREEICON_DEFAULT1           219
#define IDB_TREEICON_COMPONENT_DEFAULT  219
#define IDB_BITMAP3                     220
#define IDR_MAINFRAME_256               220
#define IDD_PROJECT_DESCRIPTION_DIALOG  221
#define IDC_CONINFO                     1000
#define IDCLGB_TREE1                    1001
#define IDC_OPTION1                     1001
#define IDCLGB_LOCATION                 1002
#define IDC_OPTION2                     1002
#define IDCLGB_OPTION                   1003
#define IDC_FIXED                       1003
#define IDCLGB_X1                       1004
#define IDC_DESCRIPTION                 1004
#define IDCLGB_X2                       1005
#define IDC_FIELD                       1005
#define IDCLGB_Y1                       1006
#define IDC_RECORD                      1006
#define IDCLGB_Y2                       1007
#define IDCLGB_DESCRIPTION              1008
#define IDC_CHECK1                      1008
#define IDCLGB_DELETE                   1009
#define IDC_CHECK2                      1009
#define IDC_STATIC2                     1010
#define IDC_CHECK3                      1010
#define ID_VERSION_DLG                  1010
#define IDCLGB_EDIT1                    1011
#define IDCLGB_SERVER                   1011
#define IDCLGB_COLOURPICKER_RESULT      1011
#define IDCLGB_PROJNAME_TEXT            1011
#define IDCLGB_FILENAME_EDIT_RO         1011
#define IDCLGB_EDIT_FILENAME            1011
#define IDC_CHECK4                      1011
#define IDC_SCRNTAG_TAG_EDIT            1011
#define IDCLGB_EDIT2                    1012
#define IDCLGB_SERVERDIR                1012
#define IDCLGB_BUTTON1                  1013
#define IDCLGB_EDIT3                    1013
#define IDCLGB_OPENPROJ_BTN             1013
#define IDCLGB_FILE_CONFIRM_BUTTON      1013
#define IDCLGB_BUTTON_SCREENTAGS        1013
#define IDCLGB_BUTTON_SCRNTAGTEST       1013
#define IDCLGB_EDIT_ORIGFILE_NAME       1013
#define IDCLGB_FG_COLOR                 1013
#define IDCLGB_TEXT_COLOR               1013
#define IDC_SCRNTAG_BUTTON_ADD          1013
#define IDCLGB_EDIT4                    1014
#define IDCLGB_BUTTON_FILEPROJMGR       1014
#define IDCLGB_EDIT_ORIGFILE_DESCRIP    1014
#define IDC_SCRNTAG_DESCR_EDIT          1014
#define IDCLGB_EDIT5                    1015
#define IDC_SCRNTAG_BUTTON_DELETE       1015
#define IDCLGB_TAG_LABEL                1016
#define IDC_SCRNTAG_EDITDESCRIP_BT      1016
#define IDCLGB_TAG                      1017
#define IDC_PARITY                      1017
#define IDC_PORT_TYPE                   1017
#define IDC_TAG_COMBO                   1017
#define IDC_ZOOM_COMBO                  1017
#define IDC_LIBRARY_COMBO               1017
#define IDCLGB_TYPE                     1018
#define IDCLGB_TYPE_LABEL               1019
#define IDCLGB_SERVER_LABEL             1020
#define IDCLGB_EDIT6                    1020
#define IDCLGB_USERNAME_LABEL           1021
#define IDCLGB_USERNAME                 1022
#define IDC_LIST                        1022
#define IDCLGB_PASSWORD                 1023
#define IDCLGB_PASSWORD_LABEL           1024
#define IDC_EDIT1                       1024
#define IDCLGB_EDIT7                    1025
#define IDC_EDIT_Y                      1025
#define IDC_BAUD                        1026
#define IDC_EDIT_WIDTH                  1026
#define IDC_SOFTWARE                    1027
#define IDC_EDIT_HEIGHT                 1027
#define IDC_BITS                        1028
#define IDC_FILENAME                    1028
#define IDC_EDIT_RED                    1028
#define IDC_STOPBITS                    1029
#define IDC_SUBJECT                     1029
#define IDC_EDIT_GREEN                  1029
#define IDC_DIRECTORY                   1030
#define IDC_EDIT_BLUE                   1030
#define IDC_MACHINE                     1031
#define IDC_EDIT_ALPHA                  1031
#define IDCLGB_COLOURPICKER             1033
#define IDCLGB_FG_COLOURPICKER          1035
#define IDCLGB_MODE1                    1036
#define IDCLGB_BG_COLOURPICKER          1036
#define IDCLGB_MODE2                    1037
#define IDCLGB_TRACK                    1038
#define IDC_EDIT_ALPHA2                 1038
#define IDCLGB_SERVERDIR_LABEL          1039
#define IDC_BLOCK_LABEL                 1039
#define IDC_EDIT_BLOCK                  1040
#define ID_TEXTBOX_OK                   1041
#define IDC_SHORT_LABEL                 1041
#define IDC_EDIT_BLOCK2                 1041
#define IDC_EDIT_MENU                   1041
#define ID_IMAGE_OK                     1042
#define IDC_EDIT_SHORT                  1042
#define ID_IMAGE_LOAD_IMAGE             1043
#define IDC_LONG_LABEL                  1044
#define IDCLGB_RADIO_BACKCOL            1045
#define IDCLGB_SCRNTAG_STATIC_TAGS      1046
#define IDC_EDIT_LONG                   1046
#define IDCLGB_LIST4                    1050
#define IDCLGB_MAIN_LIST                1050
#define IDC_STATIC_FILE                 1051
#define IDC_STATIC_SCREENTAG            1052
#define IDC_STATIC_SCREENTAG2           1053
#define IDC_STATIC_CREATE_FILENAME      1054
#define IDC_STATIC_FILENAME             1054
#define IDCLGB_CLOSEPROJ_BTN            1055
#define IDC_STATIC_DESCRIP              1055
#define IDCLGB_PFMANAGER_PROJ_GROUPBOX_STATIC 1056
#define IDC_STATIC_SCREENTAG3           1056
#define IDC_Server_Label                1056
#define IDCLGB_PFMANAGER_FILE_GROUPBOX_STATIC 1057
#define IDC_Username_label              1057
#define IDCLGB_OPENFILE_BTN             1058
#define IDCLGB_OPEN_BTN                 1058
#define IDC_USERNAME                    1058
#define IDCLGB_DELETEFILE_BTN           1059
#define IDC_Password_Label              1059
#define IDCLGB_BUTTON_SETALL            1060
#define IDCLGB_NEWFILE_BTN              1060
#define IDC_PASSWORD                    1060
#define IDC_LAB_BUTTON_SETALL           1060
#define IDCLGB_BUTTON_CLEARALL          1061
#define IDCLGB_TAGDLOG_BTN              1061
#define IDC_SERVER                      1061
#define IDC_LAB_BUTTON_CLEARALL         1061
#define IDCLGB_COPY_BTN                 1062
#define IDC_SERVERDIR_LABEL             1062
#define IDC_SERVERDIR                   1063
#define IDC_GREY_ICON                   1064
#define IDCLGB_RADIO_CURR_FOCUS_GUI     1066
#define IDCLGB_RADIO_ALL_GUIS           1067
#define IDC_BLUEICON                    1067
#define IDC_YELLOWICON                  1068
#define IDCLGB_CHECKBOX_BITMAP          1069
#define IDC_GREYICON                    1069
#define IDC_LAB_CHECKBOX_BITMAP         1069
#define IDCLGB_CHECKBOX_SODL            1070
#define IDC_BLUE_ICON                   1070
#define IDC_LAB_CHECKBOX_SODL           1070
#define IDCLGB_SETTERS_GROUP            1071
#define IDC_PURPLE_ICON                 1071
#define IDC_LAB_CHECKBOX_DATA           1071
#define ID_DISMISS                      1072
#define IDC_PURPLE_ICON_LABEL           1072
#define IDLGBTRANSFER                   1073
#define IDC_ICONS_LABEL                 1073
#define IDTRANSFER                      1073
#define IDC_LINES_LABEL                 1074
#define IDC_LAB_CHECKBOX_EXPORTED       1074
#define IDCLGB_PROGRESS2                1075
#define IDCLGB_GUIRADS_GROUP            1077
#define IDC_GUIRADS_GROUP               1077
#define IDC_GUIRADS_GROUP2              1078
#define IDC_FORCE_VALUE                 1079
#define IDCLGB_LIST                     1080
#define IDC_EDIT_VALUE                  1080
#define IDCLGB_FILE_DESC_TAG_LIST       1081
#define IDCLGB_FILE_LIST                1081
#define IDC_TIME_LABEL                  1081
#define IDCLGB_FILE_DESCRIP_LIST        1082
#define IDC_TIME_EDIT                   1082
#define IDC_NAME_LABEL                  1083
#define IDCLGB_LIST1                    1084
#define IDCLGB_LIST_TAG                 1084
#define IDCLGB_SCREEN_DESCRIP_LIST      1084
#define IDC_DIR_LABEL                   1084
#define IDCLGB_BUTTON_HDWRD1            1085
#define IDCLGB_LIST_TAG_BACK            1085
#define IDC_DIR_EDIT                    1085
#define IDCLGB_LIST2                    1086
#define IDCLGB_LIST_JUSTTAGS_BACK       1086
#define IDC_BROWSER                     1086
#define IDCLGB_BUTTON_LOAD_HRD_WRD      1087
#define IDC_NAME_EDIT                   1087
#define IDCLGB_BUTTON_CLEAR             1088
#define IDCLGB_BUTTON_LOAD_HRD_WRD2     1088
#define IDC_DEBUG_MSG                   1088
#define IDCLGB_BUTTON_HDWRD2            1089
#define IDCLGB_SCRNTAG_COMBO            1089
#define IDC_PROGRESS1                   1089
#define IDC_INSTANCE_LABEL              1090
#define IDCLGB_SCREEN_LIST              1091
#define IDC_INSTANCE_EDIT               1091
#define IDCLGB_EDIT_NEWFILE_NAME        1092
#define IDC_BLOCK_EDIT                  1092
#define IDCLGB_EDIT_NEWFILE_DESCRIP     1093
#define IDC_PORT_LABEL                  1093
#define IDCLGB_BUTTON_BG_COLOR          1094
#define IDC_PORT_EDIT                   1094
#define IDC_BLOCK_PORT_LABEL            1094
#define IDC_TYPE_LABEL                  1095
#define IDC_BLOCK_PORT_EDIT             1095
#define IDC_DATA_TYPE_LABEL             1097
#define IDC_DATA_TYPE                   1098
#define IDC_TAG_LABEL                   1099
#define IDC_ZOOM_LABEL                  1102
#define IDC_GROUP_LIST                  1103
#define IDC_ID_LABEL                    1104
#define IDC_PERIOD_LABEL                1105
#define IDC_ALLOC_LABEL                 1106
#define IDC_ADD_GROUP                   1107
#define IDC_GROUP_LABEL                 1110
#define IDC_PERIOD_EDIT                 1111
#define IDC_ALLOC_EDIT                  1112
#define IDC_EDIT_GROUP                  1113
#define IDC_DELETE_GROUP                1114
#define IDC_NAME_LIST                   1116
#define IDC_EXPORT_LIST                 1117
#define IDC_LIB_LIST                    1118
#define IDC_LIB_LABEL                   1119
#define IDC_EXPORT_LABEL                1120
#define IDC_ADD                         1121
#define IDC_DELETE                      1122
#define IDC_EDIT3                       1123
#define IDC_EDIT2                       1124
#define IDC_PROJ_DIR_EDIT               1124
#define IDC_RADIO1                      1125
#define IDC_RADIO2                      1126
#define IDC_COMPONENT_LABEL             1127
#define IDC_RADIO3                      1127
#define IDC_RADIO_BOTTOM                1127
#define IDC_LIBRARY_LABEL               1128
#define IDC_LIST1                       1129
#define IDC_PROJ_NAME_EDIT              1134
#define IDC_PROJ_NAME_LABEL             1135
#define IDC_PROJ_DIR_LABEL              1136
#define IDC_PROJ_DIR_BUTT               1137
#define IDC_PORT                        1139
#define IDC_CUSTOM1                     1140
#define IDC_WIDGET_GROUP_LABEL          1141
#define IDC_XFER_ALL                    1142
#define IDC_WIDGET_GROUP_EDIT           1142
#define IDC_STATIC_DIALOG_NUM           1143
#define IDC_WIDGET_GROUP_COMBO          1144
#define IDC_PROGRESS2                   1145
#define IDC_MENU_LABEL                  1146
#define IDC_MENU_NAME_COMBO             1147
#define IDC_COMBO1                      1148
#define IDC_MENU_NAME_LABEL             1149
#define IDC_LIST2                       1150
#define IDC_EXPLORER1                   1151
#define IDC_EDIT_X                      1152
#define IDC_CHECK_FRAME                 1153
#define IDC_RADIO_ON_TOP                1154
#define IDC_RADIO_NORMAL                1155
#define IDC_PROJECT_NAME                21001
#define IDC_PROJECT_VERSION             21002
#define IDC_PROJECT_DESCRIPTION         21003
#define IDC_PROJECT_COMMERCIALNAME      21004
#define ID_FILE_IMPORT                  32771
#define LOADAFXTAGS                     32772
#define ID_VIEWFIXED                    32772
#define ID_BUTTON32773                  32773
#define ID_VIEWDESCIPTION               32773
#define LOADAFXSODL                     32774
#define ID_MENUVIEWFIXED                32774
#define IDLGB_FTP_OPTIONS               32775
#define ID_ICON_PROPERTIES              32777
#define ID_FTP_GUI                      32778
#define ID_PROPERTIES                   32778
#define ID_LOAD_IMAGE                   32779
#define ID_DELETE_LINE                  32779
#define ID_LGBTRANSFER_OPENGUIS         32780
#define ID_DELETE_NODE                  32780
#define ID_LGBTRANSFER_ALLBITMAPS       32781
#define ID_STRAIGHTEN                   32781
#define ID_LGBTRANSFER_ALL              32782
#define ID_ICON_SHOW_DESC               32782
#define ID_LGBTRANSFER_ALLTHEABOVE      32783
#define ID_LGBTRANSFER_SODL             32784
#define ID_SUBSET                       32784
#define ID_LGBTRANSFERMANAGER           32785
#define ID_TOPDOWN                      32785
#define ID_FILE_PROJECT                 32786
#define ID_FTP_OPTIONS                  32786
#define ID_FILE_CLOSEALL                32787
#define ID_FTP_SODL                     32787
#define ID_FILE_SAVEALLGUIS             32788
#define ID_PORT_INITIALISE              32788
#define ID_FILE_DELETEGUI               32789
#define ID_CURRENT_GUI                  32791
#define ID_LGBTRANSFER_CURRENT_GUI      32792
#define ID_KEY                          32792
#define ID_LGBTRANSFER_OPEN_GUIS        32793
#define ID_ICON_CREATEINSTANCE          32793
#define ID_UP_LEVEL                     32794
#define ID_LGBTRANSFER_SODL_GUIS_BITMAPS 32795
#define ID_DEBUG_START                  32795
#define ID_HELP_ELECTRONIC_DOCS         32796
#define ID_DEBUG_STOP                   32796
#define ID_HELP_DIALOGTESTER            32797
#define ID_DEBUG_PAUSE                  32797
#define ID_HELP_DIALOGTESTER32798       32798
#define ID_DEBUG_STEP                   32798
#define ID_TEST_TESTDIALOGS             32799
#define ID_DEBUG_FORCE                  32799
#define ID_FILE_OPEN32800               32800
#define ID_LGBTRANSFER_ALL_OPEN_AND_BMP 32801
#define ID_DBGHIST_START                32801
#define ID_DBGHIST_STEP                 32802
#define ID_DBGHIST_TIME                 32803
#define ID_DBGHIST_STOP                 32804
#define ID_ICON_PROPERTIES32805         32805
#define ID_DEBUG_RESTART                32805
#define ID_NEW_PROJECT                  32812
#define ID_OPEN_PROJECT                 32814
#define ID_RELOAD_EHS                   32815
#define ID_NewSubBlock                  32818
#define ID_NEWSUBSYSTEM                 32819
#define ID_BUTTON32820                  32820
#define ID_BUTTON32821                  32821
#define ID_BUTTON32822                  32822
#define ID_BUTTON32823                  32823
#define ID_BUTTON32824                  32824
#define ID_BUTTON32825                  32825
#define ID_BUTTON32826                  32826
#define ID_BUTTON32827                  32827
#define ID_VIEW_PROJECTBAR              32828
#define ID_VIEW_PROJECT                 32829
#define ID_ICON_ADD_NAME                32830
#define ID_ADD_PORT                     32831
#define ID_DELETE_PORT                  32832
#define ID_TAG_LINE                     32833
#define ID_SHOW_LINE                    32834
#define ID_DELETE_TAG                   32835
#define ID_ADD_TAG                      32836
#define ID_VIEW_ZOOM                    32837
#define ID_WRITE_SODL                   32839
#define ID_GROUP_SETUP                  32842
#define ID_ADD_TO_GROUP                 32843
#define ID_ADD_ICON_TO_GROUP            32844
#define ID_ADD_PORT_TO_GROUP            32845
#define ID_SAVE_PROJECT                 32846
#define ID_BUTTON32847                  32847
#define ID_LIBRARY                      32848
#define ID_IMPORT_LIB                   32854
#define ID_EXPORT_LIB                   32855
#define ID_CLOSE_PROJECT                32856
#define ID_SELECT_ALL                   32857
#define ID_LUCID                        32858
#define ID_NEC                          32859
#define ID_FTP_EHS                      32860
#define ID_ZOOM_IN                      32865
#define ID_ZOOM_OUT                     32866
#define ID_FILE_IMPORTDATAFILE          32867
#define ID_IMPORT_DATA_FILE             32868
#define ID_FILE_SAVEPROJECTAS           32869
#define ID_SAVE_PROJECT_AS              32870
#define ID_EDIT_PROJECT_DESC            32871
#define ID_EDIT_DELETE                  32875
#define ID_BUTTON32877                  32877
#define ID_FILE_SCREENTAGMANAGER        32878
#define ID_TRANSFER_OPTIONS             32878
#define ID_TRANSFER_APP                 32879
#define ID_VIEW_ZOOMIN                  32880
#define ID_VIEW_ZOOMOUT                 32881
#define ID_TRANSFER_TRANSFERMANAGER     32882
#define ID_TRANSFER_MANAGER             32883
#define ID_TRANSFER_TEST                32884
#define ID_TRANSFER_LAUNCHTRANSFER      32885
#define ID_LAUNCH_TRANSFER              32886
#define ID_HELP_USERGUIDEFORLUCIDAPPLICATIONBUILDER 32887
#define ID_HELP_REFERENCEMANUALFORLUCIDAPPLICATIONBUILDER 32888
#define ID_HELP_LAB_USERGUIDE           32889
#define ID_HELP_LAB_REFMANUAL           32890
#define ID_HELP_USERGUIDEFORLUCIDAPPLICATIONBUILDER32891 32891
#define ID_HELP_REFERENCEMANUALFORLUCIDAPPLICATIONBUILDER32892 32892
#define ID_VIEW_REFRESH                 32893
#define ID_VIEW_COMPONENTPALETTE        32894
#define ID_PORT_RENAMEPORT              32895
#define ID_RENAME_PORT                  32896
#define ID_ICON_RENAMEPORT              32897
#define ID_ICON_RENAME_PORT             32898
#define ID_RENAME_XPORT                 32899
#define ID_LINE_RE                      32901
#define ID_LINE_RERoute                 32902
#define ID_LINE_REROUTE                 32903
#define ID_ICON_RE                      32904
#define ID_ICON_REROUTEALL              32905
#define ID_ADD_TO_LIBRARY               32906
#define ID_LINE_ADDNODE                 32907
#define ID_USERDEFICON_VIEWCOMPONENT    32908
#define ID_USERDEFICON_DELETEICON       32909
#define ID_USERDEFICON_PROPERTIES       32910
#define ID_USERDEFICON_RE               32911
#define ID_USERDEFICON_ADDPORT          32912
#define ID_USERDEFICON_ADDTOGROUP       32913
#define ID_USERDEFICON_ADDTOLIBRARY     32914
#define ID_XPORTICON_DELETEICON         32915
#define ID_XPORTICON_PROPERTIES         32916
#define ID_XPORTICON_RE                 32917
#define ID_XPORTICON_ADDTOGROUP         32918
#define ID_XPORTICON_RENAMEXPORT        32919
#define ID_USERDEFPORT_DELETEPORT       32920
#define ID_USERDEFPORT_SHOWLINE         32921
#define ID_USERDEFPORT_DELETETAG        32922
#define ID_USERDEFPORT_ADDTAG           32923
#define ID_USERDEFPORT_ADDTOGROUP       32924
#define ID_USERDEFPORT_RENAMEPORT       32925
#define ID_STARTPORT_INITIALISE         32926
#define ID_STARTPORT_SHOWLINE           32927
#define ID_STARTPORT_DELETETAG          32928
#define ID_STARTPORT_ADDTAG             32929
#define ID_STARTPORT_ADDTOGROUP         32930
#define ID_USERDEFSTARTPORT_INITIALISE  32931
#define ID_USERDEFSTARTPORT_DELETEPORT  32932
#define ID_USERDEFSTARTPORT_SHOWLINE    32933
#define ID_USERDEFSTARTPORT_DELETETAG   32934
#define ID_USERDEFSTARTPORT_ADDTAG      32935
#define ID_USERDEFSTARTPORT_ADDTOGROUP  32936
#define ID_USERDEFSTARTPORT_RENAMEPORT  32937
#define ID_LGB_TRANSFERALLDATA          32938
#define ID_LGB_SENDCHANGEDDATA          32939
#define ID_LAB_TRANSFERALLDATA          32940
#define ID_LAB_SENDCHANGEDDATA          32941
#define ID_OPTIONS_DEFINE               32943
#define ID_DEFINE                       32944
#define ID_DEFINE_MONITORS              32945
#define ID_OPTIONS_SELECTALLMONITORS    32946
#define ID_OPTIONS_CLEARALLMONITORS     32947
#define ID_BUTTON32948                  32948
#define ID_TRACE                        32948
#define ID_DEBUG_TRACE                  32949
#define ID_TOOLS_NATIONALLANGUAGESUPPORT 32950
#define ID_NATIONAL_LANGUAGE_SUPPORT    32951
#define ID_FILE_IMPORTRESOURCEFILE      32952
#define ID_DEBUG_STARTWITHRESTART       32953
#define ID_BUTTON32955                  32955
#define ID_EHS_MANAGEEHSLOCALLY         32958
#define ID_EHS_MANAGEEHSREMOTELY        32959
#define ID_BUTTON32961                  32961
#define ID_EHS_HOST_COMBO               32962
#define IDC_LAB_CHKBX_DISMISS_ON_COMP   33000
#define ID_HELP_TUTORIALS               33100
#define ID_LAB_EHS_START                33200
#define ID_LAB_EHS_STOP                 33201
#define ID_LAB_EHS_TOPMOST              33203
#define ID_LAB_EHS_BOTTOMMOST           33204
#define ID_LAB_EHS_NORMALZORDER         33205
#define ID_LAB_EHS_INIT_PARAMS          33206
#define ID_DELETE_RESOURCE              33207

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32963
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif



#endif

